logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"

[docker]
domain ="docker.localhost"
watch = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
 
[acme]
  email="consistentbayes@gmail.com"
  storage="acme.json"
  entryPoint="https"
  acmeLogging=true
  onDemand=true
  OnHostRule=true

[acme.httpChallenge]
  entryPoint = "http"
