# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration that uses Let's Encrypt TLS
# certificate and key.

# Extends the JupyterHub configuration in the root directory of this repository.
# Mounts an additional secrets volume that stores the Let's Encrypt TLS
# certificate and key files, and overrides the `SSL_CERT` and `SSL_KEY`
# environment variables to point to these files.

version: "2"

services:
  hub:
    extends: # hub service in repository root directory
      file: ../../docker-compose.yml
      service: hub
    volumes:
     - "secrets:/etc/letsencrypt"
    environment:
      SSL_KEY: "/etc/letsencrypt/privkey.pem"
      SSL_CERT: "/etc/letsencrypt/cert.pem"

# Explicitly declare volume and network dependencies
# (they cannot be extended)
volumes:
  data:
    external:
      name: ${DATA_VOLUME_HOST}
  secrets:
    external:
      name: ${SECRETS_VOLUME}

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
